// Mapeamento de países para emojis de bandeiras
export const countryFlags: Record<string, string> = {
  "Singapura": "🇸🇬",
  "Hong Kong": "🇭🇰",
  "Taiwan": "🇹🇼",
  "Coreia do Sul": "🇰🇷",
  "Japão": "🇯🇵",
  "China": "🇨🇳",
  "Eslovênia": "🇸🇮",
  "Suíça": "🇨🇭",
  "Holanda": "🇳🇱",
  "Coreia do Norte": "🇰🇵",
  "Macau": "🇲🇴",
  "Islândia": "🇮🇸",
  "Finlândia": "🇫🇮",
  "Canadá": "🇨🇦",
  "Bélgica": "🇧🇪",
  "Alemanha": "🇩🇪",
  "Reino Unido": "🇬🇧",
  "Áustria": "🇦🇹",
  "Nova Zelândia": "🇳🇿",
  "Israel": "🇮🇱",
  "Malta": "🇲🇹",
  "Eslováquia": "🇸🇰",
  "Noruega": "🇳🇴",
  "Suécia": "🇸🇪",
  "Luxemburgo": "🇱🇺",
  "Dinamarca": "🇩🇰",
  "República Tcheca": "🇨🇿",
  "Estônia": "🇪🇪",
  "Austrália": "🇦🇺",
  "França": "🇫🇷",
  "Itália": "🇮🇹",
  "Hungria": "🇭🇺",
  "Polônia": "🇵🇱",
  "Espanha": "🇪🇸",
  "Rússia": "🇷🇺",
  "Portugal": "🇵🇹",
  "Grécia": "🇬🇷",
  "Croácia": "🇭🇷",
  "Lituânia": "🇱🇹",
  "Letônia": "🇱🇻",
  "Irlanda": "🇮🇪",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Uruguai": "🇺🇾",
  "Costa Rica": "🇨🇷",
  "México": "🇲🇽",
  "Colômbia": "🇨🇴",
  "Venezuela": "🇻🇪",
  "Equador": "🇪🇨",
  "Peru": "🇵🇪",
  "Brasil": "🇧🇷",
  "Paraguai": "🇵🇾",
  "Bolívia": "🇧🇴",
  "Guatemala": "🇬🇹",
  "El Salvador": "🇸🇻",
  "Honduras": "🇭🇳",
  "Nicarágua": "🇳🇮",
  "Índia": "🇮🇳",
  "Indonésia": "🇮🇩",
  "Filipinas": "🇵🇭",
  "Tailândia": "🇹🇭",
  "Vietnã": "🇻🇳",
  "Malásia": "🇲🇾",
  "Mianmar": "🇲🇲",
  "Camboja": "🇰🇭",
  "Laos": "🇱🇦",
  "África do Sul": "🇿🇦",
  "Quênia": "🇰🇪",
  "Gana": "🇬🇭",
  "Nigéria": "🇳🇬",
  "Tanzânia": "🇹🇿",
  "Etiópia": "🇪🇹",
  "Uganda": "🇺🇬",
  "Zimbábue": "🇿🇼",
  "Malawi": "🇲🇼",
};

export const getCountryFlag = (country: string): string => {
  return countryFlags[country] || "🌍";
};


